sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
<<<<<<< HEAD
>>>>>>> a0ef2d3770b39b94276427186a08ce76178baafc

language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247

=======
>>>>>>> a5ba03be4ee0aa666aad61a1cc843a422550d1f7
